version: "3.9"

volumes:
  postgres_data:

services:
  gateway-service:
    build: "./gateway-service"
    ports: ["3000:80"]
    # add watch mode
    depends_on:
      - users-service

  users-service:
    build: "./users-service"
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    ports: ["3001:80"]
    volumes:
      - "./users-service:/app"
    # environment:
    #   - DATABASE_URL=postgres://postgres:password@db:5432/users
    depends_on:
      - users-service-db

  users-service-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=users-service-db
      - POSTGRES_USER=users-service-pg
      - POSTGRES_PASSWORD=12345
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
